name: windows-test
on: [push]
jobs:
  shell-cmd:
    runs-on: windows-latest
    steps:
      - name: uname-a cmd
        shell: bash
        run: uname -a
      - name: Get-ComputerInfo
        shell: pwsh
        run: Get-ComputerInfo
      - name: sys.version
        shell: python
        run: |
          import sys
          print(sys.version)
      - name: process.version
        shell: node {0}
        run: |
          console.log(process.version)

