name: Directory Navigation Exercise
on: [push]

jobs:
  directory-navigation:
    runs-on: ubuntu-latest
    steps:
      - name: Create test_folder in /home/runner
        run: mkdir -p /home/runner/test_folder
        
      - name: Create sample.txt file
        run: echo "This is a sample text file created by GitHub Actions" > /home/runner/test_folder/sample.txt
        
      - name: Check file content
        working-directory: /home/runner/test_folder
        run: cat sample.txt